### ISSUE TITLE
Is it possible to limit the dial?

### ISSUE THREAD

**Issue by skavan** [pavelkukov/react-dial-knob#4]
In other words, I wish to have:
a) the rotation of the dial only to occur between two positions (i.e. an angle offset like 8 o'clock and 4 o'clock) and
b) when reaching the end of the rotation, I don't want it to jump to the beginning.

Finally would it be easy to add labels to some of the tick marks?
A bit like this:
[Gauge](https://www.google.com/imgres?imgurl=https%3A%2F%2Fuser-images.githubusercontent.com%2F3957311%2F61056493-124dd200-a411-11e9-8a4a-9694962a1145.png&imgrefurl=https%3A%2F%2Fgithub.com%2Ftopics%2Fknob&tbnid=PHR7TVWP_tXtYM&vet=12ahUKEwj_5JrZ-7HpAhWVHt8KHeLUAysQMygLegUIARCVAg..i&docid=m_WKEy9uXPpjcM&w=382&h=300&q=react%20dial&hl=en&ved=2ahUKEwj_5JrZ-7HpAhWVHt8KHeLUAysQMygLegUIARCVAg)

**Comment by pavelkukov** [comment]
Hi @skavan ,
Thank you for the questions!

a) It is not possible to limit rotation between certain angles. Maybe in future releases. 
PRs are welcome. :)
b) Yes, you can use `spaceMaxFromZero` option to offset max from min value.

Yes, it should be easy to add labels as part of the background. 

Kind regards,
Pavel
