### ISSUE TITLE
'Value and (max - min) should be divisible by step' - could be more leniant.

### ISSUE THREAD

**Issue by xinaesthete** [pavelkukov/react-dial-knob#9]
In cases where the specific step value isn't particularly important, it's a bit annoying to have errors thrown. That might mean that I won't use this component for the time-being (admittedly I am in a bit of a rush just now, I'll likely revisit later).

I tried `value={value - (value%step)}` but with floating-point being what it is, that doesn't cut it.

Actually, I'm not sure that the internal logic is quite right either:
```ts
        if (this.value % this.step || (this.max - this.min) % this.step) {
            throw new Error(
                'Value and (max - min) should be divisible by step.',
            )
        }
```
What if one wanted to have a step of 1, but always falling at 0.5 offset, so you might have
```
min={-2.5} max={2.5} step={1} value={-1.5}
```
but your code wouldn't allow it.

Perhaps you could consider some of
- allowing `step` not to be specified
- exposing a property that would allow the user to specify whether to automatically quantize, throw an error...
- reviewing the math somewhat

Cheers

**Comment by xinaesthete** [comment]
Actually I think what I'll do for now is essentially wrap this component in something that keeps an internal value with a range 0..200 & step=1, then normalise & map back to desired range as appropriate.

**Comment by pavelkukov** [comment]
Hi @xinaesthete , your idea to wrap the component is good.
Currently, only whole numbers are supported.
